
spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      routes:
        - id: loginpage
          uri: lb://loginpage
          predicates:
            - Path=/users/**
        - id: buyerpage
          uri: lb://buyerpage
          predicates:
            - Path=/buy/**
        - id: sellerpage
          uri: lb://sellerpage
          predicates:
            - Path=/sell/**
        - id: paymentpage
          uri: lb://paymentpage
          predicates:
            - Path=/pay/**
        - id: customerrating
          uri: lb://customerrating
          predicates:
            - Path=/ratings/**
            
            